# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache-DebugLog
version:      0.01
version_from: lib/Apache/DebugLog.pm
installdirs:  site
requires:
    Apache::LogF:                  0.01
    Apache::Test:                  1
    mod_perl:                      1.2401
    mod_perl2:                     1.999022
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.28
